version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  
    healthcheck:
      test: ["CMD", "cat", "/etc/prometheus/prometheus.yml"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    depends_on:
      cadvisor:
        condition: service_healthy
      node-exporter:
        condition: service_healthy

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      prometheus:
        condition: service_healthy

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    healthcheck:
      test: ["CMD", "cat", "/dev/null"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    ports:
      - "9100:9100"
    healthcheck:
      test: ["CMD", "node_exporter", "--version"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

volumes:
  grafana_data:
