name: CI

# Trigger the workflow on push to the main branch
on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}  # Your VM's IP address
          username: ${{ secrets.USERNAME }}  # Your VM's username
          key: ${{ secrets.SSHKEY }}  # Your SSH private key
          passphrase: ${{ secrets.PASSPHRASE }}  # Passphrase for your SSH key (if any)
          script: |
            # Navigate to your project directory
            cd telegram-bot-project

            # Pull the latest changes from Git
            git pull origin main

            # Stop and remove old containers
            docker-compose down --remove-orphans || echo "No running containers to stop"

            # Rebuild and start the containers
            docker-compose up -d --build

            docker-compose -f docker-compose.monitoring.yml up -d
