name: CI

# Trigger the workflow on push to the main branch
on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Write SSH private key to file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSHKEY }}" > ~/.ssh/DO-key1_1
          chmod 600 ~/.ssh/DO-key1_1

      - name: Debug SSH connection
        run: |
          ssh -v -i ~/.ssh/DO-key1_1 -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "echo 'SSH connection successful'"

      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}  # Your VM's IP address
          username: ${{ secrets.USERNAME }}  # Your VM's username
          key: ${{ secrets.SSHKEY }}  # Your SSH private key
          passphrase: ${{ secrets.PASSPHRASE }}  # Passphrase for your SSH key (if any)
          script: |
            # Navigate to your project directory
            cd /telegram-bot-project

            # Pull the latest changes from Git
            git pull origin main

            # Stop and remove old containers
            docker-compose down || echo "No running containers to stop"

            # Rebuild and start the containers
            docker-compose up -d --build
